# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import vision_pb2 as vision__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in vision_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VisionServiceStub:
    """============================================
    Services
    ============================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CaptureScreen = channel.unary_unary(
                '/hcs.vision.v1.VisionService/CaptureScreen',
                request_serializer=vision__pb2.CaptureRequest.SerializeToString,
                response_deserializer=vision__pb2.CaptureResponse.FromString,
                _registered_method=True)
        self.StreamFrames = channel.unary_stream(
                '/hcs.vision.v1.VisionService/StreamFrames',
                request_serializer=vision__pb2.StreamFramesRequest.SerializeToString,
                response_deserializer=vision__pb2.FrameChunk.FromString,
                _registered_method=True)
        self.ListMonitors = channel.unary_unary(
                '/hcs.vision.v1.VisionService/ListMonitors',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=vision__pb2.MonitorList.FromString,
                _registered_method=True)
        self.DetectObjects = channel.unary_unary(
                '/hcs.vision.v1.VisionService/DetectObjects',
                request_serializer=vision__pb2.DetectionRequest.SerializeToString,
                response_deserializer=vision__pb2.DetectionResponse.FromString,
                _registered_method=True)
        self.BatchDetectObjects = channel.unary_unary(
                '/hcs.vision.v1.VisionService/BatchDetectObjects',
                request_serializer=vision__pb2.BatchDetectionRequest.SerializeToString,
                response_deserializer=vision__pb2.BatchDetectionResponse.FromString,
                _registered_method=True)
        self.RecognizeText = channel.unary_unary(
                '/hcs.vision.v1.VisionService/RecognizeText',
                request_serializer=vision__pb2.OcrRequest.SerializeToString,
                response_deserializer=vision__pb2.OcrResponse.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/hcs.vision.v1.VisionService/GetModelInfo',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=vision__pb2.ModelList.FromString,
                _registered_method=True)
        self.ReloadModels = channel.unary_unary(
                '/hcs.vision.v1.VisionService/ReloadModels',
                request_serializer=vision__pb2.ReloadModelsRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/hcs.vision.v1.VisionService/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=vision__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/hcs.vision.v1.VisionService/GetConfig',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=vision__pb2.VisionConfig.FromString,
                _registered_method=True)
        self.UpdateConfig = channel.unary_unary(
                '/hcs.vision.v1.VisionService/UpdateConfig',
                request_serializer=vision__pb2.VisionConfig.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class VisionServiceServicer:
    """============================================
    Services
    ============================================

    """

    def CaptureScreen(self, request, context):
        """Screen capture
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFrames(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMonitors(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectObjects(self, request, context):
        """Object detection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchDetectObjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecognizeText(self, request, context):
        """OCR
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """Model management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadModels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health & Config
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VisionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CaptureScreen': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureScreen,
                    request_deserializer=vision__pb2.CaptureRequest.FromString,
                    response_serializer=vision__pb2.CaptureResponse.SerializeToString,
            ),
            'StreamFrames': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFrames,
                    request_deserializer=vision__pb2.StreamFramesRequest.FromString,
                    response_serializer=vision__pb2.FrameChunk.SerializeToString,
            ),
            'ListMonitors': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMonitors,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=vision__pb2.MonitorList.SerializeToString,
            ),
            'DetectObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectObjects,
                    request_deserializer=vision__pb2.DetectionRequest.FromString,
                    response_serializer=vision__pb2.DetectionResponse.SerializeToString,
            ),
            'BatchDetectObjects': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchDetectObjects,
                    request_deserializer=vision__pb2.BatchDetectionRequest.FromString,
                    response_serializer=vision__pb2.BatchDetectionResponse.SerializeToString,
            ),
            'RecognizeText': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeText,
                    request_deserializer=vision__pb2.OcrRequest.FromString,
                    response_serializer=vision__pb2.OcrResponse.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=vision__pb2.ModelList.SerializeToString,
            ),
            'ReloadModels': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadModels,
                    request_deserializer=vision__pb2.ReloadModelsRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=vision__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=vision__pb2.VisionConfig.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=vision__pb2.VisionConfig.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'hcs.vision.v1.VisionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('hcs.vision.v1.VisionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VisionService:
    """============================================
    Services
    ============================================

    """

    @staticmethod
    def CaptureScreen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hcs.vision.v1.VisionService/CaptureScreen',
            vision__pb2.CaptureRequest.SerializeToString,
            vision__pb2.CaptureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFrames(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/hcs.vision.v1.VisionService/StreamFrames',
            vision__pb2.StreamFramesRequest.SerializeToString,
            vision__pb2.FrameChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMonitors(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hcs.vision.v1.VisionService/ListMonitors',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            vision__pb2.MonitorList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hcs.vision.v1.VisionService/DetectObjects',
            vision__pb2.DetectionRequest.SerializeToString,
            vision__pb2.DetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchDetectObjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hcs.vision.v1.VisionService/BatchDetectObjects',
            vision__pb2.BatchDetectionRequest.SerializeToString,
            vision__pb2.BatchDetectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecognizeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hcs.vision.v1.VisionService/RecognizeText',
            vision__pb2.OcrRequest.SerializeToString,
            vision__pb2.OcrResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hcs.vision.v1.VisionService/GetModelInfo',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            vision__pb2.ModelList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hcs.vision.v1.VisionService/ReloadModels',
            vision__pb2.ReloadModelsRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hcs.vision.v1.VisionService/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            vision__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hcs.vision.v1.VisionService/GetConfig',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            vision__pb2.VisionConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/hcs.vision.v1.VisionService/UpdateConfig',
            vision__pb2.VisionConfig.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
